#!/usr/bin/env bash
# extract-secrets.sh — (re)generate monitoring/secrets.env from n8n's credential store.
# Run ON the VPS as root. Secrets are written straight to a chmod-600 file and
# never printed. Re-run after rotating any credential in n8n.
set -eu
MON_DIR="/mnt/chinmay-astro-data/monitoring"
TMP=$(mktemp)
trap 'rm -f "$TMP"; docker exec n8n-prod rm -f /tmp/_creds.json 2>/dev/null || true' EXIT

docker exec n8n-prod n8n export:credentials --all --decrypted --output=/tmp/_creds.json >/dev/null 2>&1
docker exec n8n-prod cat /tmp/_creds.json > "$TMP"

SLACK=$(jq -r '[.[]|select(.type=="slackApi")][0].data.accessToken'        "$TMP")
GEMINI=$(jq -r '[.[]|select(.type=="googlePalmApi")][0].data.apiKey'        "$TMP")
WA_TOKEN=$(jq -r '[.[]|select(.type=="whatsAppApi")][0].data.accessToken'   "$TMP")
WA_WABA=$(jq -r '[.[]|select(.type=="whatsAppApi")][0].data.businessAccountId' "$TMP")

for v in "$SLACK" "$GEMINI" "$WA_TOKEN" "$WA_WABA"; do
  if [ -z "$v" ] || [ "$v" = "null" ]; then
    echo "ERROR: a required credential field was empty — aborting, secrets.env left unchanged." >&2
    exit 1
  fi
done

mkdir -p "$MON_DIR/state"
umask 077
cat > "$MON_DIR/secrets.env" <<EOF
# Generated by extract-secrets.sh from n8n's credential store. chmod 600, VPS-only, NOT committed.
# Re-run scripts/monitoring/extract-secrets.sh after rotating any of these in n8n.
SLACK_BOT_TOKEN=$SLACK
SLACK_ALERT_CHANNEL=C0A5B0ZE81E
GEMINI_API_KEY=$GEMINI
WHATSAPP_TOKEN=$WA_TOKEN
WHATSAPP_WABA_ID=$WA_WABA
EOF
chmod 600 "$MON_DIR/secrets.env"
echo "secrets.env written: $(wc -l < "$MON_DIR/secrets.env") lines, mode $(stat -c '%a' "$MON_DIR/secrets.env")"
